### ISSUE TITLE
Support for multi-platform/universal wiring

### ISSUE THREAD

**Issue by mgolfieri** [MickGyver/DaemonBite-Arcade-Encoder#1]
It would be great to be able use the same platform wiring for all. Say you have the Arcade wiring, you can switch to control an Amiga or NeoGeo with the same setup, just by switching mapping in SW.  At the end of the day, GND and +V are going to be in the same spot, everything else should be doable as pure signals?

**Comment by sorgelig** [comment]
From my point of view it's better to stick to the same adapter without jumping between different ones. Arduino Micro is dirt cheap, so just buy several boards and make adapters specific to different controllers and then update the FW only within the same adapter.
The project is targeted to simpliest way to build with minimum additional components. And this is a big advantage over universal adapters adjusting their pins to different controllers and require more complex wiring or even additional board.

**Comment by MickGyver** [comment]
I agree with Sorgelig. Marcello, the adapters will work for various cores without rewiring anything, you can map the controller for each core in the menu on the MiSTer any way you want.

**Comment by mgolfieri** [comment]
thank you both, makes sense.  Closing!
