### ISSUE TITLE
"menu ok" action : impossible to assign

### ISSUE THREAD

**Issue by robinmasters2** [MickGyver/DaemonBite-Arcade-Encoder#10]
hello,
I've just setup an arduino pro micro and loaded it with the arcade encoder software.
I use it on mister. 

The issue I'm having  is that, when assigning the buttons for the mister menu, a double clic is happening when assigning the "menu ok" action. in consequence It also assigns the "menu back" action on the same button.

it's only happening is this particular situation.
in game no double click. 
it happens whathever the button is. 

after sharing with friends, looks like two of my pals are expériencing the same issue. 
is there already a workaround ? 

thank you.

**Comment by 0x15e** [comment]
You need to enable debounce in the source and reflash your Arduino. It should be as simple as uncommenting one line.

**Comment by robinmasters2** [comment]
thank you it worked !
