### ISSUE TITLE
[FR] switchable Xinput mode

### ISSUE THREAD

**Issue by eadmaster** [MickGyver/DaemonBite-Arcade-Encoder#13]
not sure if doable, btw some commercial controllers allow you to switch from XInput<->DInput mode for better compatibility with newer/older games.

Another reason to switch back to DInput is to have [lower latencies as suggested here](https://github.com/dmadison/ArduinoXInput/issues/49#issuecomment-787410909).

**Comment by sigboe** [comment]
The Daemonbite arcade encoder has an average latency of 0.758 ms, with standard deviation of 0.289. In a 60fps game this gives a same frame probability of 95.45% This is tested by Porkchop Express from https://misteraddons.com (input latency in the top menu as source)

I dont think there is anything to get from switching to dinput, but have you looked at this line? https://github.com/MickGyver/DaemonBite-Arcade-Encoder/blob/master/DaemonBiteArcadeEncoder/DaemonBiteArcadeEncoder.ino#L26
