### ISSUE TITLE
In emulationstation problem

### ISSUE THREAD

**Issue by Luciano2018** [MickGyver/DaemonBite-Arcade-Encoder#5]
Hi, thanks for this great code, is really fast, have a problem with the joystick, mine have switches instead of potenciometers, this maybe, cause that when choose console or game, step 4 consoles or games only pressing once the joystick, in the game works great, but can figureout how to fix it, try ps3 and neogeo option, the same issue

**Comment by 0x15e** [comment]
I had a similar problem with my build. Try looking in the source for the place where debounce is configured and enable it. That took care of my problem and didn't add any discernable lag.

**Comment by Luciano2018** [comment]
Thanks for the quick help, i try your solution, hope too works🙏 cause the code its amazing.

**Comment by Luciano2018** [comment]
Thank so much!!! Hours try different things and the answer already there hehe . For someone else with this Not an Issue, the simple solution is, in the sketch(DaemonBiteArcadeEncoder.ino), just change this line:
#define DEBOUNCE 0
to
#define DEBOUNCE 1

compile and upload just that, thanks again for the really fast help. Now i can play without lags and perfect in a pi 4, with pi os in retropie 4.7.9. Thanks!

**Comment by juri74** [comment]
> 
> 
> Thank so much!!! Hours try different things and the answer already there hehe . For someone else with this Not an Issue, the simple solution is, in the sketch(DaemonBiteArcadeEncoder.ino), just change this line:
> #define DEBOUNCE 0
> to
> #define DEBOUNCE 1
> 
> compile and upload just that, thanks again for the really fast help. Now i can play without lags and perfect in a pi 4, with pi os in retropie 4.7.9. Thanks!

thanks but this will add 10ms of lag!

**Comment by Luciano2018** [comment]
> > Thank so much!!! Hours try different things and the answer already there hehe . For someone else with this Not an Issue, the simple solution is, in the sketch(DaemonBiteArcadeEncoder.ino), just change this line:
> > #define DEBOUNCE 0
> > to
> > #define DEBOUNCE 1
> > compile and upload just that, thanks again for the really fast help. Now i can play without lags and perfect in a pi 4, with pi os in retropie 4.7.9. Thanks!
> 
> thanks but this will add 10ms of lag!

I dont have tools for measure delay, in real life isn't difference Jury, is working perfectly my joystick, i push all buttons without delay, and in the readme page of this code say that delay is max 1.28ms . I dont notice any change when change debounce to 1 , if in laboratory the delay change to 10ms i couldn't see any difference. By the way, zero delay board have 15ms of delay, so equally we have -5ms of delay with this code. In my particular case, i can play games with debounce 0, but in the menu emulationstation all go wrong, like if we push Re Pág in a text processor(the behaviour). So if you want the minimum delay posible(readme) just use the code like it is, with debounce 0, and navigate emulationstation with a keyboard or ir control, but if you want manage with your diy joystick at emulationstation then put debounce 1, is just a choice, in both case no visible delay in real world, if you notice it, maybe check your solder joints with a tester, checking a correct continuity, and dont put large cable, just the correct large for make the solder. You can see my tutorial with my diy joystick with this cool code if you google my name "Luciano Rabassa". Give it a try to this code, MickGyver make a great work!!!

**Comment by MickGyver** [comment]
The debounce function will only add about 32µs of lag, not 10ms.
/MickGyver    On Thursday, April 1, 2021, 05:31:30 PM GMT+3, Raspberry Pi Buenos Aires ***@***.***> wrote:  
 
 




Thank so much!!! Hours try different things and the answer already there hehe . For someone else with this Not an Issue, the simple solution is, in the sketch(DaemonBiteArcadeEncoder.ino), just change this line:
#define DEBOUNCE 0
to
#define DEBOUNCE 1
compile and upload just that, thanks again for the really fast help. Now i can play without lags and perfect in a pi 4, with pi os in retropie 4.7.9. Thanks!


thanks but this will add 10ms of lag!


I dont have tools for measure delay, in real life isn't difference Jury, is working perfectly my joystick, i push all buttons without delay, and in the readme page of this code say that delay is max 1.28ms . I dont notice any change when change debounce to 1 , if in laboratory the delay change to 10ms i couldn't see any difference. By the way, zero delay board have 15ms of delay, so equally we have -5ms of delay with this code. In my particular case, i can play games with debounce 0, but in the menu emulationstation all go wrong, like if we push Re Pág in a text processor(the behaviour). So if you want the minimum delay posible(readme) just use the code like it is, with debounce 0, and navigate emulationstation with a keyboard or ir control, but if you want manage with your diy joystick at emulationstation then put debounce 1, is just a choice, in both case no visible delay in real world, if you notice it, maybe check your solder joints with a tester, checking a correct continuity, and dont put large cable, just the correct large for make the solder. You can see my tutorial with my diy joystick with this cool code if you google my name "Luciano Rabassa". Give it a try to this code, MickGyver make a great work!!!

**Comment by Luciano2018** [comment]
Thanks for the real tech answer your code rocks 😎 Really thanks 👏👏👏

**Comment by juri74** [comment]
Thank you! i read the 10ms on the code, 32µs is nothing :)
